# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8326a4ba30030ddd89c84d6ea7ebf3f0fe1bd6f1c824fa31bbb9cbc4cbab4a41fd1a31acc763bfe0acfdb260b35e3c6c933a179b59bd4030126283a1be13ed3

test:
  secret_key_base: 527df1afa2847bf0fcaa254e119a81efcf79acd347bc8ac33a2e7db5537314a0c63da98930cae90381c80e6926b40f97fde7ac4cb361d30c3ac1e06f3a40e5dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
